[tool.poetry]
name = "devnotes"
version = "0.1.0"
description = ""
authors = ["Fang Liu <fyliu@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^6.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
